// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyFilesBasedOnPrefix(arg1) {
  return window['go']['main']['App']['CopyFilesBasedOnPrefix'](arg1);
}

export function DecodeFilenames(arg1) {
  return window['go']['main']['App']['DecodeFilenames'](arg1);
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function ReplaceFilenames(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReplaceFilenames'](arg1, arg2, arg3);
}
