// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyFilesBasedOnPrefix(arg1:string):Promise<void>;

export function DecodeFilenames(arg1:string):Promise<void>;

export function OpenFolder():Promise<string>;

export function ReplaceFilenames(arg1:string,arg2:string,arg3:string):Promise<void>;
